#!/usr/bin/env zsh


STOWFOLDERS="awesome,nvim,zsh,alacritty"

pushd $DOTFILES
for folder in $(echo $STOWFOLDERS | sed "s/,/ /g")
do
    echo "Installing $folder"
    stow -D $folder
    stow $folder
done
popd
